language: en
pipeline:
  # - name: ConveRTTokenizer
  #   case_sensitive: False
  # - name: ConveRTFeaturizer
  - name: SpacyNLP
    model: "en_core_web_md"
    case_sensitive: False
  - name: WhitespaceTokenizer
    case_sensitive: False
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
  - name: "DucklingHTTPExtractor"
    url: "http://localhost:8000"
    dimensions: ["time", "number", "duration"]
    locale: "en_GB"
    timezone: "America/Montreal"
  - name: SpacyEntityExtractor
    dimensions: ["CARDINAL", "LOC"]
    locale: "en_GB"
    timezone: "Asia/Mumbai"

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: MappingPolicy
  - name: "FormPolicy"
